version: "3.1"

services:
  web:
    image: "my-registry:55000/pluralsight-admin-web-image"
    #ports:
    #  - "8080:80"
  api:
    image: "my-registry:55000/pluralsight-admin-api-image"
    #ports:
    #  - "3001:3001"
  test:
    image: "my-registry:55000/pluralsight-admin-integration-image"
    build: .
    environment:
      - NETWORK_VAR=api
